#!/bin/bash

jupyter nbconvert --to markdown $1 --stdout | sed "s/\\$/\\$\\$/g" | sed "s/\\\left\\\{/\\\left\\\\\\\{/g" | sed "s/\\\right\\\}/\\\right\\\\\\\}/g" | sed "s/}}_/}}\\\_/g" >> ../_posts/$2
